name: Infrastructure
on: [push]

jobs:
  build:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      working-directory: ./terraform
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: terraform init
      working-directory: ./terraform
    - run: terraform apply -auto-approve
      working-directory: ./terraform