name: Infrastructure
on:
  push:
    paths:
      - "terraform/**"

jobs:
  build:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        env:
          TF_WORKSPACE: production
        working-directory: ./terraform
      - run: terraform apply -auto-approve
        env:
          TF_WORKSPACE: production
        working-directory: ./terraform
