name: Client
on:
  push:
    paths:
    - 'src/**'
    - 'content/**'
    - 'static/**'

jobs:
  build:
    name: Test & Deploy Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: npm install
    - run: npm run build
    - run: npm test
      env:
        CI: true
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: davidvargas.me
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        SOURCE_DIR: "public"