name: Testing
on:
  push:
    paths:
    - 'src/**'

jobs:
  build:
    name: Test Client Src
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: npm install
    - run: npm run build
    - run: npm test
      env:
        CI: true